apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.app.suffix }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.app.path }}
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.app.name }}-{{ .Values.app.suffix }}"
            port:
              number: 80