apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.app.suffix }}"
  labels:
    app: "{{ .Values.app.name }}-{{ .Values.app.suffix }}"
    chart: {{ template "webapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.app.name }}-{{ .Values.app.suffix }}"
    release: {{ .Release.Name }}
