name: Build webapp

on: [push]

jobs:
  build_and_push:
    name: Push webapp image to docker hub
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Auth to ACR
        uses: azure/docker-login@v1
        with:
          login-server: acmellc.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"

      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            acmellc.azurecr.io/webapp:${{ steps.vars.outputs.short_sha }}
            acmellc.azurecr.io/webapp:latest
  deploy:
    needs: build_and_push
    name: Deploy to Kubernetes DEV Cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context aks-sandbox
    - name: Deploy to K8s
      run: helm upgrade -f helm/webapp/values.yaml webapp helm/webapp/ -n dev